# Generated by Django 5.2.9 on 2026-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
