# Generated by Django 5.2.9 on 2026-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_last_notified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="last_notified",
        ),
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
    ]
