# Generated by Django 5.2.9 on 2026-01-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habit_last_notified_alter_habit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время обновления"
            ),
        ),
    ]
